name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages

    env:
      VITE_API_URL: ${{ secrets.VITE_API_URL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
          cache-dependency-path: ./client/pnpm-lock.yaml

      - name: Install dependencies
        working-directory: ./client
        run: pnpm install --frozen-lockfile

      - name: Build
        working-directory: ./client
        run: pnpm build

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy client/build/client --project-name=sakuya10969-portfolio-client
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
